2025-01-18 10:55:44,482:DEBUG:certbot._internal.main:certbot version: 3.1.0
2025-01-18 10:55:44,483:DEBUG:certbot._internal.main:Location of certbot entry point: /lsiopy/bin/certbot
2025-01-18 10:55:44,483:DEBUG:certbot._internal.main:Arguments: ['--config-dir', '/config/etc/letsencrypt', '--logs-dir', '/config/log/letsencrypt', '--work-dir', '/tmp/letsencrypt', '--config', '/config/etc/letsencrypt/cli.ini', '--non-interactive', '--renew-by-default']
2025-01-18 10:55:44,486:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#certbot-route53:auth,PluginEntryPoint#cpanel,PluginEntryPoint#dns-acmedns,PluginEntryPoint#dns-aliyun,PluginEntryPoint#dns-azure,PluginEntryPoint#dns-bunny,PluginEntryPoint#dns-cloudflare,PluginEntryPoint#dns-desec,PluginEntryPoint#dns-digitalocean,PluginEntryPoint#dns-directadmin,PluginEntryPoint#dns-dnsimple,PluginEntryPoint#dns-dnsmadeeasy,PluginEntryPoint#dns-dnspod,PluginEntryPoint#dns-do,PluginEntryPoint#dns-domeneshop,PluginEntryPoint#dns-dreamhost,PluginEntryPoint#dns-duckdns,PluginEntryPoint#dns-dynu,PluginEntryPoint#dns-freedns,PluginEntryPoint#dns-gandi,PluginEntryPoint#dns-gehirn,PluginEntryPoint#dns-glesys,PluginEntryPoint#dns-godaddy,PluginEntryPoint#dns-google,PluginEntryPoint#dns-he,PluginEntryPoint#dns-hetzner,PluginEntryPoint#dns-infomaniak,PluginEntryPoint#dns-inwx,PluginEntryPoint#dns-ionos,PluginEntryPoint#dns-linode,PluginEntryPoint#dns-loopia,PluginEntryPoint#dns-luadns,PluginEntryPoint#dns-namecheap,PluginEntryPoint#dns-netcup,PluginEntryPoint#dns-njalla,PluginEntryPoint#dns-nsone,PluginEntryPoint#dns-ovh,PluginEntryPoint#dns-porkbun,PluginEntryPoint#dns-rfc2136,PluginEntryPoint#dns-route53,PluginEntryPoint#dns-sakuracloud,PluginEntryPoint#dns-standalone,PluginEntryPoint#dns-transip,PluginEntryPoint#dns-vultr,PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2025-01-18 10:55:44,521:DEBUG:certbot._internal.log:Root logging level set at 30
2025-01-18 10:55:44,522:DEBUG:certbot._internal.plugins.selection:Requested authenticator standalone and installer None
2025-01-18 10:55:44,522:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * standalone
Description: Runs an HTTP server locally which serves the necessary validation files under the /.well-known/acme-challenge/ request path. Suitable if there is no HTTP server already running. HTTP challenge only (wildcards not supported).
Interfaces: Authenticator, Plugin
Entry point: EntryPoint(name='standalone', value='certbot._internal.plugins.standalone:Authenticator', group='certbot.plugins')
Initialized: <certbot._internal.plugins.standalone.Authenticator object at 0x7eff42b374d0>
Prep: True
2025-01-18 10:55:44,523:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot._internal.plugins.standalone.Authenticator object at 0x7eff42b374d0> and installer None
2025-01-18 10:55:44,523:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator standalone, Installer None
2025-01-18 10:55:44,524:DEBUG:certbot._internal.client:Registering without email!
2025-01-18 10:55:44,726:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2025-01-18 10:55:45,242:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sat, 18 Jan 2025 04:55:45 GMT
Content-Type: application/json
Content-Length: 828
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "profiles": {
      "classic": "The same profile you're accustomed to"
    },
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.4-April-3-2024.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "renewalInfo": "https://acme-v02.api.letsencrypt.org/draft-ietf-acme-ari-03/renewalInfo",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert",
  "xBzEajfaNMc": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417"
}
2025-01-18 10:55:45,242:DEBUG:acme.client:Requesting fresh nonce
2025-01-18 10:55:45,242:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2025-01-18 10:55:45,410:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sat, 18 Jan 2025 04:55:45 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 695xoWTD7aipaC9YJEnpqBVrHIn-AWe1sHcIQKSnx6MSsVTHunE
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2025-01-18 10:55:45,410:DEBUG:acme.client:Storing nonce: 695xoWTD7aipaC9YJEnpqBVrHIn-AWe1sHcIQKSnx6MSsVTHunE
2025-01-18 10:55:45,410:DEBUG:acme.client:JWS payload:
b'{\n  "termsOfServiceAgreed": true\n}'
2025-01-18 10:55:45,416:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-acct:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAiandrIjogeyJuIjogImw1M2p0YjhtWC1zQ0hESG9BNWFvU0xxZ0llbTlKNGVIaXV6dGVLQ052ejhKWWhBTV9jZjlwVllIVk4xaU5ZSjBmc1BQNk1oQ3lIeWJUVDJTYUw2SWR1UWRoOUdlc3I5eUF4NWMzRnhWY1ZKT2I0Q0c2YTZmQm5UN09xUURmMEhibkZXcUQtNnNMWFN5S0dpdUxTNTlzSnFOSk9faXJ5UzVsZDBNeG1pZ3NZX2hHdF9fT0tKUkg5VmZqNER0RGk4RkVFb1RvQlRHWUE5aWxUNkVpLURUaERDWXJ5ZGtTY1NnbXlLYVByZmxrQWhJa092ZkRoM0lDT1h6MVMtamNVUDh1OU1EWlM3WlZORWUwb0NaMnIxMW5ub0k1dVRqdDlzeEtCYkJ3akN5TUY4QnFkTzBRNHowSDFNY1BEdFZ4dFNkRVM2N3F5elBMRjUxRWhIR0lWVHljdyIsICJlIjogIkFRQUIiLCAia3R5IjogIlJTQSJ9LCAibm9uY2UiOiAiNjk1eG9XVEQ3YWlwYUM5WUpFbnBxQlZySEluLUFXZTFzSGNJUUtTbng2TVNzVlRIdW5FIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9uZXctYWNjdCJ9",
  "signature": "UaMPHOXoH-HbjPwAdPbjtErGZPgZ3EzOrqHRiNqprM18RQAeVdJTJPr35Deaadad1ZDDbeIq3rIEKzZo242vKZHFCjuu9dDqWw9QKAzJRBFeZy-yI5pDO2YTNI8zwegGvHvNTOyPFGCZ710ajt-wAEmuH9fzHzqp056bIzKS8MPh2-o6BRM8kdmWYIRzu7NkwUGm1TbpJaTuWz2RhCSOXBm5VsclQn_tl5REVvw865XVDf9LH6SZKNYjahoBcSWcaOm3a4iRBfVrOjPo5q3MsNVriADjoaHJOWKueb1Q_y25XF6k_064MIxxY9n8RvDYkjXqucE5AbvMBp2JdzrBEQ",
  "payload": "ewogICJ0ZXJtc09mU2VydmljZUFncmVlZCI6IHRydWUKfQ"
}
2025-01-18 10:55:45,604:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Date: Sat, 18 Jan 2025 04:55:45 GMT
Content-Type: application/json
Content-Length: 477
Connection: keep-alive
Boulder-Requester: 2176770265
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index", <https://letsencrypt.org/documents/LE-SA-v1.4-April-3-2024.pdf>;rel="terms-of-service"
Location: https://acme-v02.api.letsencrypt.org/acme/acct/2176770265
Replay-Nonce: 695xoWTD0LvjAaa09nVSikqlfGfNg9Sv6JEUzDkk7H6Vs4RzzaU
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "key": {
    "kty": "RSA",
    "n": "l53jtb8mX-sCHDHoA5aoSLqgIem9J4eHiuzteKCNvz8JYhAM_cf9pVYHVN1iNYJ0fsPP6MhCyHybTT2SaL6IduQdh9Gesr9yAx5c3FxVcVJOb4CG6a6fBnT7OqQDf0HbnFWqD-6sLXSyKGiuLS59sJqNJO_iryS5ld0MxmigsY_hGt__OKJRH9Vfj4DtDi8FEEoToBTGYA9ilT6Ei-DThDCYrydkScSgmyKaPrflkAhIkOvfDh3ICOXz1S-jcUP8u9MDZS7ZVNEe0oCZ2r11nnoI5uTjt9sxKBbBwjCyMF8BqdO0Q4z0H1McPDtVxtSdES67qyzPLF51EhHGIVTycw",
    "e": "AQAB"
  },
  "createdAt": "2025-01-18T04:55:45.514789108Z",
  "status": "valid"
}
2025-01-18 10:55:45,605:DEBUG:acme.client:Storing nonce: 695xoWTD0LvjAaa09nVSikqlfGfNg9Sv6JEUzDkk7H6Vs4RzzaU
2025-01-18 10:55:45,609:DEBUG:certbot._internal.display.obj:Notifying user: Account registered.
2025-01-18 10:55:45,609:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=JWKRSA(key=<ComparableRSAKey(<cryptography.hazmat.bindings._rust.openssl.rsa.RSAPublicKey object at 0x7eff42bde2f0>)>), contact=(), agreement=None, status='valid', terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/2176770265', new_authzr_uri=None, terms_of_service='https://letsencrypt.org/documents/LE-SA-v1.4-April-3-2024.pdf'), 39021b3109869cd2bf5cb92b8c5d8a87, Meta(creation_dt=datetime.datetime(2025, 1, 18, 4, 55, 45, tzinfo=<UTC>), creation_host='c0785c6e0e72', register_to_eff=None))>
2025-01-18 10:55:45,611:DEBUG:certbot._internal.display.obj:Notifying user: Requesting a certificate for re-works.ru
2025-01-18 10:55:45,618:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "re-works.ru"\n    }\n  ]\n}'
2025-01-18 10:55:45,620:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMjE3Njc3MDI2NSIsICJub25jZSI6ICI2OTV4b1dURDBMdmpBYWEwOW5WU2lrcWxmR2ZOZzlTdjZKRVV6RGtrN0g2VnM0Unp6YVUiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL25ldy1vcmRlciJ9",
  "signature": "PAIujaJpxTz8LNI7x0Fccc4-kImiZPWOZvGSNqhtAsWLEY7HNDImchC3pdIJCJDdhiKbPyra2G45y0QTfblWZ9DYrgdQnD-ydBX6gmdFvs-otdpd9u1rKRYhyQHNjoVI-oUXh5esuh4ughrXBy8PxMtqALUQDvX2-wC4ky-XVfpcArFniRKEOxgObqW11kw49_lz-XG2MKJ3jILwFE5XjFgPLI8rzYKxmz-oncaBa8FC0IXyGmPi0gnUqXzJOB4n8jyG-CpJCkUcJ-VyfXtX5mdzMtlq0i5uV4cWoUaMCDE-CPIYlUYCtKQu4Nxb5c5palPuFcVYGLQtWuejW-lVgQ",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogInJlLXdvcmtzLnJ1IgogICAgfQogIF0KfQ"
}
2025-01-18 10:55:45,827:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Date: Sat, 18 Jan 2025 04:55:45 GMT
Content-Type: application/json
Content-Length: 345
Connection: keep-alive
Boulder-Requester: 2176770265
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Location: https://acme-v02.api.letsencrypt.org/acme/order/2176770265/345497445595
Replay-Nonce: 695xoWTDjSvR2BX9feqTGQZcw3W8TBfOF4J4PVZJzfjsLWR56oI
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "status": "pending",
  "expires": "2025-01-25T04:55:45Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "re-works.ru"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz/2176770265/462345561295"
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/2176770265/345497445595"
}
2025-01-18 10:55:45,828:DEBUG:acme.client:Storing nonce: 695xoWTDjSvR2BX9feqTGQZcw3W8TBfOF4J4PVZJzfjsLWR56oI
2025-01-18 10:55:45,828:DEBUG:acme.client:JWS payload:
b''
2025-01-18 10:55:45,830:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz/2176770265/462345561295:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMjE3Njc3MDI2NSIsICJub25jZSI6ICI2OTV4b1dURGpTdlIyQlg5ZmVxVEdRWmN3M1c4VEJmT0Y0SjRQVlpKemZqc0xXUjU2b0kiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2F1dGh6LzIxNzY3NzAyNjUvNDYyMzQ1NTYxMjk1In0",
  "signature": "VTjbPGQTnzQ7L07U9bfWBm4RF0Z3jxQzFT54xk61nI0bGrjFWcTEo_rSZ-WbmMMNZkFknJzHl9opF4fB9oTy1uty9pK_j-n2ycxHt-GuMJy9Qll66gsPC545XNLwyDbGhH-i-QP4wuOcfNif6Nw3ABj_eOtIammbKZlf1X_jBPlKk41nmzG9bctafAljVQrme3PVO5I6IN42vWNyFijwJce55ycEEYke3wqo702KsjjVhQa7HVnnROMqeLPnbOeba-DflWWtd_sNx7pe7scHl2NVQ8zZtGgdI7c-MmSKdYNVpv_6ZIVIQ3VDvT5I_kWBVdJ8nrTAn0or15xyvUMI8g",
  "payload": ""
}
2025-01-18 10:55:46,004:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sat, 18 Jan 2025 04:55:45 GMT
Content-Type: application/json
Content-Length: 819
Connection: keep-alive
Boulder-Requester: 2176770265
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: TuPv3OuuolQvhW4nbAIYqWYCs2uPEzGimI5LG9Rrp3hN8tZWTrk
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "re-works.ru"
  },
  "status": "pending",
  "expires": "2025-01-25T04:55:45Z",
  "challenges": [
    {
      "type": "tls-alpn-01",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall/2176770265/462345561295/R7D1XA",
      "status": "pending",
      "token": "GAcPLB9stJoh4r_EUA0NOq68dcDawJnYlA2xWxrxt6w"
    },
    {
      "type": "http-01",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall/2176770265/462345561295/Aq7e6A",
      "status": "pending",
      "token": "GAcPLB9stJoh4r_EUA0NOq68dcDawJnYlA2xWxrxt6w"
    },
    {
      "type": "dns-01",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall/2176770265/462345561295/KTEHKQ",
      "status": "pending",
      "token": "GAcPLB9stJoh4r_EUA0NOq68dcDawJnYlA2xWxrxt6w"
    }
  ]
}
2025-01-18 10:55:46,004:DEBUG:acme.client:Storing nonce: TuPv3OuuolQvhW4nbAIYqWYCs2uPEzGimI5LG9Rrp3hN8tZWTrk
2025-01-18 10:55:46,005:INFO:certbot._internal.auth_handler:Performing the following challenges:
2025-01-18 10:55:46,005:INFO:certbot._internal.auth_handler:http-01 challenge for re-works.ru
2025-01-18 10:55:46,005:DEBUG:acme.standalone:Successfully bound to :80 using IPv6
2025-01-18 10:55:46,005:DEBUG:acme.standalone:Certbot wasn't able to bind to :80 using IPv4, this is often expected due to the dual stack nature of IPv6 socket implementations.
2025-01-18 10:55:46,007:DEBUG:acme.client:JWS payload:
b'{}'
2025-01-18 10:55:46,008:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/chall/2176770265/462345561295/Aq7e6A:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMjE3Njc3MDI2NSIsICJub25jZSI6ICJUdVB2M091dW9sUXZoVzRuYkFJWXFXWUNzMnVQRXpHaW1JNUxHOVJycDNoTjh0WldUcmsiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2NoYWxsLzIxNzY3NzAyNjUvNDYyMzQ1NTYxMjk1L0FxN2U2QSJ9",
  "signature": "RQtqGxjGtNJRR85i-WzrKCL6y9aPA4Jj-z8fbUeNBitnEtp51VAvZAc7MY6PTzZhVmP-zbZFTSOdhfz-ZhSlEtG7Ge_Y8utfmcbpdEMxmZxqUnaX442cjtub8o0U6TNJi5zkHPN8qFya1KvGrYT0Sv4XT1P850zs-Y0z3hjcDlOtqP0EppizZG_6YEYVJEpWwS-H1MZ9GIYSN5g3jKPIvDBZYJqSNMj70dJQITyco0C0MZZ4bEwAXFlotSqWEJ2rjXRUAaHU93FOBAN19osdTGXQuDkI2_vkmzEq7gITmuKzOJ8vphBO7kRBDNizuCB0qkV7uLRUUumkWX0qyX1Awg",
  "payload": "e30"
}
2025-01-18 10:55:46,181:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sat, 18 Jan 2025 04:55:46 GMT
Content-Type: application/json
Content-Length: 195
Connection: keep-alive
Boulder-Requester: 2176770265
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index", <https://acme-v02.api.letsencrypt.org/acme/authz/2176770265/462345561295>;rel="up"
Location: https://acme-v02.api.letsencrypt.org/acme/chall/2176770265/462345561295/Aq7e6A
Replay-Nonce: 695xoWTDUhy9x6PtD09IMzu5PPXi6ypcqmW5RydOPhsNmbSnZTA
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "type": "http-01",
  "url": "https://acme-v02.api.letsencrypt.org/acme/chall/2176770265/462345561295/Aq7e6A",
  "status": "pending",
  "token": "GAcPLB9stJoh4r_EUA0NOq68dcDawJnYlA2xWxrxt6w"
}
2025-01-18 10:55:46,181:DEBUG:acme.client:Storing nonce: 695xoWTDUhy9x6PtD09IMzu5PPXi6ypcqmW5RydOPhsNmbSnZTA
2025-01-18 10:55:46,181:INFO:certbot._internal.auth_handler:Waiting for verification...
2025-01-18 10:55:47,182:DEBUG:acme.client:JWS payload:
b''
2025-01-18 10:55:47,184:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz/2176770265/462345561295:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMjE3Njc3MDI2NSIsICJub25jZSI6ICI2OTV4b1dURFVoeTl4NlB0RDA5SU16dTVQUFhpNnlwY3FtVzVSeWRPUGhzTm1iU25aVEEiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2F1dGh6LzIxNzY3NzAyNjUvNDYyMzQ1NTYxMjk1In0",
  "signature": "e7JAaZztkT3B1fb4mobPA-bWxE5EWSWRvzodxp9Wy-hPltLD5MideZ5_-XNEsh7sJTy44G38LjPPs6XPLiJr9EgSAAFw72lI9zKkLAre16P_JDxdb5CnYaGG5WH8yv8Y6KCFesYR8zgIXU5c_OZ2OFIx9QXKqkh7GgwaXHpFJQMi8mNQGz35CH1BV0RiKUkv2JRd2InTU6YE2Us2BrUpou8h2kEJanmD70vHLAxrVcdALu5NIQO5SeNdP8viSLqnmeasE50leouBe3F2Z16FJQ8ZB1ZNo6Nf_742od8qsstpF8fQK-WwMNONSD4JIe65yOJ7sui60hP2dfkGcVoiSQ",
  "payload": ""
}
2025-01-18 10:55:47,354:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sat, 18 Jan 2025 04:55:47 GMT
Content-Type: application/json
Content-Length: 1081
Connection: keep-alive
Boulder-Requester: 2176770265
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 695xoWTDW-HK8yH6-mHIxVYxUTWuQst6bcZHHlNFaGIsCFiWp90
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "re-works.ru"
  },
  "status": "invalid",
  "expires": "2025-01-25T04:55:45Z",
  "challenges": [
    {
      "type": "http-01",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall/2176770265/462345561295/Aq7e6A",
      "status": "invalid",
      "validated": "2025-01-18T04:55:46Z",
      "error": {
        "type": "urn:ietf:params:acme:error:unauthorized",
        "detail": "2a03:6f00:6:1::57f9:2b15: Invalid response from http://re-works.ru/.well-known/acme-challenge/GAcPLB9stJoh4r_EUA0NOq68dcDawJnYlA2xWxrxt6w: 404",
        "status": 403
      },
      "token": "GAcPLB9stJoh4r_EUA0NOq68dcDawJnYlA2xWxrxt6w",
      "validationRecord": [
        {
          "url": "http://re-works.ru/.well-known/acme-challenge/GAcPLB9stJoh4r_EUA0NOq68dcDawJnYlA2xWxrxt6w",
          "hostname": "re-works.ru",
          "port": "80",
          "addressesResolved": [
            "84.38.181.11",
            "2a03:6f00:6:1::57f9:2b15"
          ],
          "addressUsed": "2a03:6f00:6:1::57f9:2b15"
        }
      ]
    }
  ]
}
2025-01-18 10:55:47,354:DEBUG:acme.client:Storing nonce: 695xoWTDW-HK8yH6-mHIxVYxUTWuQst6bcZHHlNFaGIsCFiWp90
2025-01-18 10:55:47,355:INFO:certbot._internal.auth_handler:Challenge failed for domain re-works.ru
2025-01-18 10:55:47,355:INFO:certbot._internal.auth_handler:http-01 challenge for re-works.ru
2025-01-18 10:55:47,355:DEBUG:certbot._internal.display.obj:Notifying user: 
Certbot failed to authenticate some domains (authenticator: standalone). The Certificate Authority reported these problems:
  Domain: re-works.ru
  Type:   unauthorized
  Detail: 2a03:6f00:6:1::57f9:2b15: Invalid response from http://re-works.ru/.well-known/acme-challenge/GAcPLB9stJoh4r_EUA0NOq68dcDawJnYlA2xWxrxt6w: 404

Hint: The Certificate Authority failed to download the challenge files from the temporary standalone webserver started by Certbot on port 80. Ensure that the listed domains point to this machine and that it can accept inbound connections from the internet.

2025-01-18 10:55:47,358:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/lsiopy/lib/python3.12/site-packages/certbot/_internal/auth_handler.py", line 108, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, max_time_mins, best_effort)
  File "/lsiopy/lib/python3.12/site-packages/certbot/_internal/auth_handler.py", line 212, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.

2025-01-18 10:55:47,358:DEBUG:certbot._internal.error_handler:Calling registered functions
2025-01-18 10:55:47,358:INFO:certbot._internal.auth_handler:Cleaning up challenges
2025-01-18 10:55:47,358:DEBUG:certbot._internal.plugins.standalone:Stopping server at :::80...
2025-01-18 10:55:47,512:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/lsiopy/bin/certbot", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/certbot/_internal/main.py", line 1873, in main
    return config.func(config, plugins)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/certbot/_internal/main.py", line 1579, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/certbot/_internal/main.py", line 142, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/certbot/_internal/client.py", line 518, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/certbot/_internal/client.py", line 429, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/certbot/_internal/client.py", line 497, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, self.config, best_effort)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/certbot/_internal/auth_handler.py", line 108, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, max_time_mins, best_effort)
  File "/lsiopy/lib/python3.12/site-packages/certbot/_internal/auth_handler.py", line 212, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.
2025-01-18 10:55:47,516:ERROR:certbot._internal.log:Some challenges have failed.
